export interface CalendarEvent {
    id: string;
    title: string;
    startTime: string;
    endTime: string;
    date: string;
    participants: string[];
    meetingLink?: string;
    timezone?: string;
}

export const events: CalendarEvent[] = [
    {
        id: "1",
        title: "Daily checkin",
        startTime: "09:00",
        endTime: "10:00",
        date: "2024-02-04",
        participants: ["user1", "user2", "user3"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "2",
        title: "Call with Leonel Ngoya - UX Designer",
        startTime: "10:00",
        endTime: "11:30",
        date: "2024-02-04",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "3",
        title: "Quick Sync",
        startTime: "12:00",
        endTime: "12:15",
        date: "2024-02-04",
        participants: ["user1"],
    },
    {
        id: "4",
        title: "Lunch Meeting",
        startTime: "13:00",
        endTime: "14:00",
        date: "2024-02-04",
        participants: ["user1", "user2"],
    },
    {
        id: "5",
        title: "Team Standup",
        startTime: "14:00",
        endTime: "14:30",
        date: "2024-02-04",
        participants: ["user1", "user2", "user3", "user4"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "6",
        title: "Design Review",
        startTime: "15:00",
        endTime: "15:45",
        date: "2024-02-04",
        participants: ["user1", "user2", "user3"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "7",
        title: "Product Review",
        startTime: "16:00",
        endTime: "17:00",
        date: "2024-02-04",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "8",
        title: "Client Call",
        startTime: "17:30",
        endTime: "18:00",
        date: "2024-02-04",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "9",
        title: "Evening Standup",
        startTime: "19:00",
        endTime: "19:15",
        date: "2024-02-04",
        participants: ["user1", "user2"],
    },
    {
        id: "10",
        title: "Night Sync",
        startTime: "22:00",
        endTime: "22:30",
        date: "2024-02-04",
        participants: ["user1"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "11",
        title: "Early Morning Check",
        startTime: "06:00",
        endTime: "06:30",
        date: "2024-02-05",
        participants: ["user1"],
    },
    {
        id: "12",
        title: "Daily checkin",
        startTime: "09:00",
        endTime: "10:00",
        date: "2024-02-05",
        participants: ["user1", "user2", "user3"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "13",
        title: "Call with James Brown - UX Designer",
        startTime: "10:00",
        endTime: "11:00",
        date: "2024-02-05",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "14",
        title: "Quick Update",
        startTime: "11:30",
        endTime: "11:45",
        date: "2024-02-05",
        participants: ["user1"],
    },
    {
        id: "15",
        title: "Design Workshop",
        startTime: "13:00",
        endTime: "15:00",
        date: "2024-02-05",
        participants: ["user1", "user2", "user3"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "16",
        title: "Coffee Break",
        startTime: "15:30",
        endTime: "15:45",
        date: "2024-02-05",
        participants: [],
    },
    {
        id: "17",
        title: "Sprint Review",
        startTime: "16:00",
        endTime: "17:00",
        date: "2024-02-05",
        participants: ["user1", "user2", "user3", "user4"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "18",
        title: "Client Meeting",
        startTime: "18:00",
        endTime: "19:00",
        date: "2024-02-05",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "19",
        title: "Dinner Meeting",
        startTime: "20:00",
        endTime: "21:00",
        date: "2024-02-05",
        participants: ["user1", "user2"],
    },
    {
        id: "20",
        title: "Late Night Work",
        startTime: "23:00",
        endTime: "23:30",
        date: "2024-02-05",
        participants: ["user1"],
    },
    {
        id: "21",
        title: "Morning Exercise",
        startTime: "07:00",
        endTime: "07:30",
        date: "2024-02-06",
        participants: [],
    },
    {
        id: "22",
        title: "Daily checkin",
        startTime: "09:00",
        endTime: "10:00",
        date: "2024-02-06",
        participants: ["user1", "user2", "user3"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "23",
        title: "Intro call with Nova - Product Manager",
        startTime: "10:00",
        endTime: "11:30",
        date: "2024-02-06",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "24",
        title: "Intro call with Chris - Bubble Developer",
        startTime: "12:00",
        endTime: "13:30",
        date: "2024-02-06",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
        timezone: "UTC",
    },
    {
        id: "25",
        title: "Afternoon Break",
        startTime: "14:00",
        endTime: "14:15",
        date: "2024-02-06",
        participants: [],
    },
    {
        id: "26",
        title: "Sprint Planning",
        startTime: "15:00",
        endTime: "16:30",
        date: "2024-02-06",
        participants: ["user1", "user2", "user3", "user4"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "27",
        title: "Code Review",
        startTime: "17:00",
        endTime: "17:30",
        date: "2024-02-06",
        participants: ["user1", "user2"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "28",
        title: "Team Dinner",
        startTime: "19:00",
        endTime: "20:30",
        date: "2024-02-06",
        participants: ["user1", "user2", "user3"],
    },
    {
        id: "29",
        title: "Evening Review",
        startTime: "21:00",
        endTime: "21:30",
        date: "2024-02-06",
        participants: ["user1"],
        meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
        id: "30",
        title: "Midnight Check",
        startTime: "00:00",
        endTime: "00:30",
        date: "2024-02-07",
        participants: ["user1"],
    },
];

export const getTodayEvents = () => {
    const today = new Date().toISOString().split('T')[0];
    return events.filter(event => event.date === today);
};

export const addEvent = (event: Omit<CalendarEvent, "id">) => {
    const newEvent = {
        ...event,
        id: Math.random().toString(36).substr(2, 9),
    };
    events.push(newEvent);
    return newEvent;
};
